name: CroniServer
version: ${project.version}
api-version: ${apiVersion}
main: com.monstahhh.croniserver.plugin.croniserver.CroniServer
authors: [monstahhhy]
softdepend: [AuthMe, DiscordSRV]

commands:
  hub:
    description: Takes you to the hub
    usage: /hub

  survival:
    description: Takes you to survival
    usage: /survival

  creative:
    description: Takes you to creative
    usage: /creative

  uhcpractice:
    description: Takes you to the UHC Practice world
    usage: /uhcpractice

  stopuhc:
    description: Stops your UHC Session
    usage: /stopuhc

  clearuhcplayers:
    description: Clears UHC Players
    usage: /clearuhcplayers

  home:
    description: Takes you to your home
    usage: /home

  sethome:
    description: Sets your home to your current location
    usage: /sethome

  distance:
    description: Shows you the distance to a certain point
    usage: /distance x y z

  pdistance:
    description: Shows you the distance to a certain player
    usage: /pdistance playername

  lol:
    description: xd
    usage: /lol

  spawn:
    description: Takes you to spawn
    usage: /spawn