name: CroniServer
version: 1.5.1-SHAPSHOT
api-version: 1.14
main: com.monstahhh.croniserver.plugin.croniserver.CroniServer
authors: [monstahhhy]
softdepend: [AuthMe]

commands:

  home:
    description: Takes you to your home
    usage: /home

  sethome:
    description: Sets your home to your current location
    usage: /sethome

  distance:
    description: Shows you the distance to a certain point
    usage: /distance x y z

  pdistance:
    description: Shows you the distance to a certain player
    usage: /pdistance player

  lol:
    description: xd
    usage: /lol

  hub:
    description: Takes you to the hub
    usage: /hub

  spawn:
    description: Takes you to spawn
    usage: /spawn

  crinfo:
    description: Info about CroniServer
    usage: /crinfo