name: CroniServer
version: 1.4.8
api-version: 1.14
main: com.monstahhh.croniserver.plugin.croniserver.CroniServer
authors: [monstahhhy]
softdepend: [AuthMe]

commands:
  distance:
    description: Shows you the distance to a certain point
    usage: /distance x y z

  pdistance:
    description: Shows you the distance to a certain player
    usage: /pdistance player

  lol:
    description: xd
    usage: /lol

  hub:
    description: Takes you to the hub
    usage: /hub

  spawn:
    description: Takes you to spawn
    usage: /spawn

  info:
    description: Info about CroniServer
    usage: /info