name: CroniServer
version: 1.0
api-version: 1.13
main: com.monstahhh.croniserver.plugin.croniserver.CroniServer
authors: [monstahhhy]

commands:
  distance:
    description: Shows you the distance to a certain point
    usage: /distance x y z

  pdistance:
    description: Shows you the distance to a certain player
    usage: /pdistance player

  lol:
    description: xd
    usage: /lol

  hub:
    description: Takes you to the hub
    usage: /hub